<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fluxtemplate"
 *
 * Auto generated by Extension Builder 2015-11-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid: Website Template',
	'description' => 'A smart foundation to start with your website. Supports all Bootstrap Elements. Make your TYPO3 Responsive using SCSS, Bootstrap, HTML5 Boilerplate and jQuery.',
	'category' => 'misc',
	'author' => 'Vijay Rami',
	'author_email' => 'vijay.rami@webofficeindia.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'flux' => '',
            'vhs' => '',
            'fluidcontent' => '',
            'fluidpages' => '',
            'ws_scss' => '',
            'seo_basics' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);